.gitlab-ci.yml
=> feat(ci): use remote include

.gitlab-ci.yml
=> ci(gitlab): refactor gitlab pipelines

Dockerfile
=> fix(docker): set NEXT_TELEMETRY_DISABLED=1

.editorconfig, .github/renovate.json, .github/stale.yml, .renovaterc.json
=> chore(github): add basic stale bot

.dockerignore
=> chore(docker): ignore more files

.gitlab-ci.yml, .releaserc.yml
=> ci(gitlab): add release job

.gitlab-ci.yml
=> ci(gitlab): share create namespace stage

.gitlab-ci.yml
=> ci(gitlab): share deploy nodejs chart stage

.dockerignore, .gitlab-ci.yml, Dockerfile
=> build(docker): speed up the build

.gitlab-ci.yml, .k8s/app.values.yml
=> feat(k8s): use wild card certificate

Dockerfile
This reverts commit e4e443f0b56aed8b9e11d208a45a02bec02aef6e.
=> Revert "chore(deps): update node.js to v13 (#72)"

src/sentry.js
Fixed
```
[ error ] ./node_modules/destroy/index.js
Module not found: Can't resolve 'fs' in '**/node_modules/destroy'
```
https://github.com/zeit/next.js/issues/9768
https://github.com/zeit/next.js/commit/a7e96706fcbe10fab2bc1909eca67c5b4886e58c
=> Fixed Sentry config to development issue

.k8s/app.values.yml
=> build(k8s): override default app name

package.json, src/pages/_app.js, src/pages/_document.js, yarn.lock
=> feat: import bootstrap from npm

.babelrc, src/__tests__/api/[query].test.js
=> test(api): add api test

.k8s/app.values.yml
=> build: use prod url in k8s values

.k8s/app.values.yml
=> build(k8s): change liveness readiness port

src/pages/_document.js
this removes dependency to our unmaintained polyfill instance.
recommended way is to extract adequate polyfills from polyfill.io
=> chore: remove polyfill

package.json, yarn.lock
=> fix(deps): update all non-major dependencies

.gitlab-ci.yml, .k8s.app.values.yml, Dockerfile
=> ci(gitlab): update to SocialGouv/gitlab-ci-yml#autodevops 12.0.0

Dockerfile, yarn.lock
=> build(docker): use node:12.16.2

.k8s.app.values.yml
=> build(k8s): change app name

.gitlab-ci.yml, .k8s/environments/.gitlab.env, CHANGELOG.md, package.json
SocialGouv/gitlab-ci-yml#douglasduteil/feat-kosko-share-env-with-the-user
=> fix(gitlab): test k8s testing in releases

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap, .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/__tests__/kosko generate --env dev.ts, .k8s/__tests__/kosko generate --env preprod.ts, .k8s/__tests__/kosko generate --env prod.ts, .k8s/components/_pgweb.ts, .k8s/components/app.ts, .k8s/components/hasura.ts, .k8s/package.json, .k8s/yarn.lock, Dockerfile, hasura/Dockerfile
use latest CI, kaniko + harbor with GitLab group
=> fix: kaniko + harbor

.k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap, .k8s/package.json, .k8s/yarn.lock
=> fix(build): update @socialgouv/kosko-charts (minor)
